### ISSUE TITLE
Krakend custom router implementation for mapping all paths using '*' as regular expression

### ISSUE THREAD

**Issue by weworksonam** [devopsfaith/krakend-ce#107]
I am looking to map all inbound paths for example such "/api/\*" to "/backend/*" application.
Is there any example where I can build this functionality?  I am assuming this would need to be a custom router implementation.

**Comment by alombarte** [comment]
Hi @weworksonam , please have a look at this issue https://github.com/devopsfaith/krakend-ce/issues/30

In fact, that would be a custom router implementation.

**Comment by weworksonam** [comment]
I saw that Github issue earlier too. I was wondering if there were some best practices or samples on how to best implement it.  Ofcourse, I do realize the API gateway to be use-case specific.  Just would be great if you could show some samples as this seems to be a somewhat a desired feature.

**Comment by taik0** [comment]
I think that the [httptreemux](https://github.com/devopsfaith/krakend/tree/master/router/httptreemux) router implementation supports wildcards in the routes.

**Comment by weworksonam** [comment]
How would I apply or invoke the httptreemux router in my endpoint definition in krakend.json config?

**Comment by kpacha** [comment]
@weworksonam the KrakenD-CE comes with the gin router. There is no way to enable any of the other router implementations available at the framework at running time.

If you want to change the set of components included into the CE you'll need to fork it and code your customizations.

One last thing, no router implementation in the KrakenD framework accepts wildcards. There are several reasons and @alombarte added a link to other issue with some of them. But even with a customized router it will be hard to support wildcards because the lack of info regarding the extracted params (aka, how to map something unknown into something also unknown?)

cheers!

**Comment by weworksonam** [comment]
Thanks @kpacha .  It makes sense why wildcards are not supported and is a bad practice anyways.
