### ISSUE TITLE
Confused newbie

### ISSUE THREAD

**Issue by mlamothe** [devopsfaith/krakend-ce#119]
I'm new to KrakenD - checking it out to see if it would meet our needs. The feature set looks very good, but now I need to actually get a proof of concept running.

KrakenD-CD looks interesting. So I'm on this page: https://www.krakend.io/docs/overview/krakend-vs-krakend-ce/, reading about the Community Edition, and there's a download button. I click that, and it just brings me to the download page for the framework... which I've already installed. So I go back and click the repo link, which brings me to this git repo... The readme has tons of links pointing me back to the framework docs where I just was...

I'm confused - what am I supposed to be doing to use CE? Is it part of the framework I've already downloaded? If so, what are the details? Or am I supposed to clone the git repo and build it myself? And then what?

I guess what I'm looking for is some kind of "Getting started with KrakenD Community Edition" instructions. Sorry if I'm blind and just not seeing it.

One last thing: The line "The good news is that we always refer to both things as “KrakenD” :)" doesn't help me at all.

I appreciate your help.

**Comment by alombarte** [comment]
Thanks Marcel,

I'll try to improve the documentation because having the engine (krakend) and the software (krakend-ce) might be confusing.

**Anything you can download from the website is KrakenD-CE**. And 99% of the pages of the website are referring to KrakenD-CE too unless it's otherwise noticed.

The framework cannot be installed as it is a library to build custom gateways. The only way to use it is by going to Github, clone the project and compile a custom version with go by yourself.

 If you are a docker user the best way to get started is by just executing this:
```
docker run -p 8080:8080 -v $PWD:/etc/krakend/ devopsfaith/krakend run --config /etc/krakend/krakend.json
```

If you are looking for other installation/running options, see: https://www.krakend.io/docs/overview/installing/

But bottom line, you don't need to compile anything to use KrakenD-CE. Let me know if this helps

Thanks

**Comment by mlamothe** [comment]
Thanks, that helps clear up a lot -- I appreciate it!

**Comment by alombarte** [comment]
Feel free to reopen or ask again here or in Slack.
