### ISSUE TITLE
[QUESTION] Manipulating Requests

### ISSUE THREAD

**Issue by belljustin** [devopsfaith/krakend-ce#143]
Newbie to krakend and wondering if it can let me manipulate requests before passing them to the backend.

For example, I might have a backend that wants a request shaped like,

POST /users
{
  "user" {
     "type": "customer",
     "email": <customer_email>
  }
}

But I want a proxy endpoint that looks like,

POST /customers
{
  "email": <customer_email>
}

Any tips on how to do this? I've seen the martian body.modifier but not sure how to use this dynamically.

**Comment by kpacha** [comment]
By default, request bodies are not modified by the KrakenD pipes. But there are some ways to achieve what you want (each one requires a different level of 'effort' and offers a different level of performance):

1. Build a custom plugin (it doesn't matter if it's a http handler or a http client) (no CE compilation required, but the plugin should be compiled) check this in order to get an idea of how the KrakenD plugin system works: https://www.krakend.io/blog/krakend-grpc-gateway-plugin/
2. Build a custom martial modifier (this requires to import it and recompile your CE). An example: https://www.krakend.io/blog/website-development-as-a-sysadmin/
3. Add a custom LUA snippet (this is the single dynamic solution, but it's also the worst one from the performance point of view). From the integration tests: https://github.com/devopsfaith/krakend-ce/blob/0.10-dev/tests/fixtures/krakend.json#L469-L490 and https://github.com/devopsfaith/krakend-ce/blob/0.10-dev/tests/fixtures/lua/collection.lua
