### ISSUE TITLE
 unable to create the GELF writer

### ISSUE THREAD

**Issue by pmonsan** [devopsfaith/krakend-ce#202]
I can't run the Docker Krakend image
I get this error :
ERROR unable to create the GELF writer: getting the extra config for the krakend-gelf module

**Comment by bollohz** [comment]
Any news on that?

**Comment by taik0** [comment]
This message only means that there's no defined configuration for the GELF Writer so it wont be used.

**Comment by shamsg** [comment]
so how i can overcome this error?

**Comment by alombarte** [comment]
It's only an error if you are exporting logs using GELF @shamsg. Are you?

## If you are not using GELF

During startup, KrakenD will try to load configuration for all its possible modules. If a specific module does not have its definition in the configuration file you will see an ERROR telling you that KrakenD was unable to load the module. This error is just informational and it only has a meaning if you were actually trying to use it. It can be ignored unless you are using this functionality.

For instance, if you start krakend with the smallest `krakend.json` configuration file possible:
```
{
    "version": "2"
}
```
You should at the very least see these errors:
```
2020/11/27 09:50:40  ERROR: unable to create the gologging logger: getting the extra config for the krakend-gologging module
2020/11/27 09:50:40  ERROR: unable to create the GELF writer: getting the extra config for the krakend-gelf module
```

As you can see the configuration file in the example define neither `krakend-gologging` nor `krakend-gelf`, and KrakenD will notify you in case you were expecting something different.

But in the end, if the process does not die is that KrakenD is listening and working (or otherwise you would see a panic and an exit)

## If you are using GELF

Make sure to pass the right configuration:
```
"extra_config": {
  "github_com/devopsfaith/krakend-gelf": {
    "address": "myGraylogInstance:12201",
    "enable_tcp": false
  }
  "github_com/devopsfaith/krakend-gologging": {
      "level": "INFO",
      "prefix": "[KRAKEND]",
      "syslog": false,
      "stdout": true
  }
}
```
