### ISSUE TITLE
Uncommon 503 status code when maxRate limit is reached

### ISSUE THREAD

**Issue by mkjsix** [devopsfaith/krakend-ce#250]
Hi all,

Just a quick question: the docs says that when maxRate limit is reached then the response is `503 Service Unavailable`, while I would have expected a much more common `429 Too many requests`.

A client usually interprets a 5xx error as a server malfunction, while in case of reaching a max rate I'd say the problem resides on the client side. IMO, in this situation the 429 error code looks much more informative about the exact issue.

For example, that is what the AWS API Gateway returns in this case: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html

**Comment by mkjsix** [comment]
I saw that you use the 429 response for the `clientMaxRate` and 503 for `maxRate`, which makes sense to me.

**Comment by kpacha** [comment]
as you already saw, the ratelimit component returns more than one status code, depending on the case.

- a 429 is returned when the rate limiter is defined by some token in order to throttle clients (by user identity, IP, cookies, headers, etc)
- a 503 is returned when the rate limit is defined for a given point in the path in order to throttle the load of one or several backends

we'll check the documentation

**Comment by alombarte** [comment]
The documentation could be better, but it's documented:

- https://www.krakend.io/docs/endpoints/rate-limit/#what-if-the-clientmaxrate-limit-is-reached
- https://www.krakend.io/docs/endpoints/rate-limit/#what-if-the-maxrate-limit-is-reached
