### ISSUE TITLE
Improvements to Dockerfile

### ISSUE THREAD

**Issue by samstride** [devopsfaith/krakend-ce#274]
Hi,

The current `Dockerfile.alpine` produces an image which is about `56.6 MB` in size.

Security of the Dockerfile can be improved by using a [distroless container](https://github.com/GoogleContainerTools/distroless).

It also results in a Dockerfile of size `24.11 MB` -> [see here](https://hub.docker.com/r/ownage/krakend/tags?page=1&ordering=last_updated)

```dockerfile
FROM golang:1.15.2-alpine3.12 as builder

WORKDIR /app

RUN apk add --no-cache make curl git build-base

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make build

FROM gcr.io/distroless/static:latest-amd64

LABEL maintainer="dortiz@devops.faith"

COPY --from=builder /app/krakend /usr/bin/krakend

VOLUME [ "/etc/krakend" ]

ENTRYPOINT [ "/usr/bin/krakend" ]
CMD [ "run", "-c", "/etc/krakend/krakend.json" ]

EXPOSE 8000 8090
```

Also, I am curious as to why there are 2 Dockerfile's in the repo?

Thanks.

**Comment by alombarte** [comment]
Hello @samstride ,

Thanks for the contribution. Yes, we have two docker images in our repo:

- The Docker alpine image (unpublished)
- The Debian slim image (official image)
 
The official image is based on Debian buster slim (which is actually a very small image). On every release, we push it to the registry.

The Alpine Dockerfile is on the repo for people looking for an image with a smaller footprint, but we stopped publishing it to the hub because of the number of questions and support tickets we receive when people use it in conjunction with plugins.

Our default official image needs to be able to provide all KrakenD functionality, and this includes plugins.  With distroless or Alpine this is not possible.

We could replace Alpine with distroless (if we prove that works ok) and scratch some more MB, but I wanted to let you know the status of Dockerfile

Thanks!
