### ISSUE TITLE
Critical Issue with / in Parameters

### ISSUE THREAD

**Issue by egandro** [devopsfaith/krakend-ce#290]
Krakend has a bug with parsing parameters.

**Your configuration file** (part of a multiconfig /template file)
```
    {
      "endpoint": "/bar/api/hello/{name}",
      "method": "GET",
      "host": "http://172.17.0.1:8012",
      "url_pattern": "/api/hello/{name}",
      "backend": "greeter"
    },
```

```
# name = "World"
$ curl -X GET "http://localhost:8080/bar/api/hello/World" -H  "accept: application/json"
[00] [GIN] 2021/04/09 - 17:25:51 | 200 |     841.749µs |      172.17.0.1 | GET      "/bar/api/hello/World"
```

This will fail! It is not the endpoint "/bar/api/hello". Some bug in krakend will call the endpoint "/bar/api/hello/World/of/bugs"

```
# name = "World/of/bugs"
$curl -X GET "http://localhost:8080/bar/api/hello/World%2Fof%2Fbugs" -H  "accept: application/json"
[00] [GIN] 2021/04/09 - 17:28:23 | 404 |      21.715µs |      172.17.0.1 | GET      "/bar/api/hello/World/of/bugs"
```

krakend will urldecode the parameters before it is putting it on the endpoint. Expected behavior - don't do that urldecoding.

```
[00] [GIN] 2021/04/09 - 17:31:12 | 200 |    1.530413ms |      172.17.0.1 | GET      "/bar/api/hello/World%2Fof%2Fbugs

```

Krakend version:

```
RUN git clone https://github.com/devopsfaith/krakend-ce.git \
	&& cd krakend-ce \
    && git reset --hard f77ed77
```

**Comment by alombarte** [comment]
Hi @egandro,
This is a misinterpretation of what KrakenD should do. A parameter is not meant to be a quick passage to wildcard behavior.
Please see the documentation: https://www.krakend.io/docs/endpoints/creating-endpoints/#endpoint-variables

**Comment by amarktl** [comment]
Hi @alombarte, @egandro 

I have not yet tried to reproduce this issue - but as far as i understand @egandro  he wants to have the value **World/of/bugs** which is already *urlencoded* in the initial call to be mapped to the path parameter **{name}** as is.

`curl -X GET "http://localhost:8080/bar/api/hello/World%2Fof%2Fbugs" -H  "accept: application/json"`

For met this sounds like a valid use case - the urlencoded parameter should not be decoded on its way to the backend OR it should perform an additional encoding before creating the backend url.  

BR,
Alex

**Comment by egandro** [comment]
Dear @alombarte 

Yes as @amarktl  mentiones - this **is** a bug.

This is the Enpoint: "endpoint": "/user/{name}",

id is "World%2Fof%2Fbugs" that is a valid string for an name, Check Java Spring, NodeJS, PHP, DotnetCore and other samples.

KrakenD will urldecode that and make a "World/of/bugs" out of that string. The expected behavior - do not do that! and send send "World%2Fof%2Fbugs" to the endpoint as name.

**Comment by egandro** [comment]
Dear @alombarte 

I am willing to do whatever it takes.

Do you want a full feature blown example showing this Bug?

I can make a small Repo with a krakend.conf and a sample go REST server.

**Comment by alombarte** [comment]
I am reopening the issue so @kpacha can have a look.

**Comment by egandro** [comment]
Dear @kpacha,

I am willing to help. If you need simple example just ask and I provide you with a repo (GO server) and a krakend.conf.

**Comment by kpacha** [comment]
This is not a bug, it's a design choice.

KrakenD is not a reverse proxy, it's a gateway designed to build tailored, RESTful APIs for your clients. That's why wildcards are not supported and why we kept disabled the `UseRawPath` flag from the router (https://pkg.go.dev/github.com/gin-gonic/gin#Engine), meaning that the reserved chars defined at https://tools.ietf.org/html/rfc1738#section-2.2 should be decoded by the gateway in order to properly routing the request. I think we need to improve our documentation on this topic since the limitation you're facing is not mentioned (as it also happens with the `:` character)

> %E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD <- equivalent of a lot of utf-8 encoded characters for "中华人民共和国," (China)

KrakenD is build with go, so it's able to deal with any utf8 character (you can check this example: https://play.golang.org/p/AHFfiENz6f0). Some KrakenD users even define their endpoints with emoticons (such as /tasks/😀)

Also, this is the default way of dealing with url paths in go (https://golang.org/pkg/net/url/#URL):

>  Note that the Path field is stored in decoded form: /%47%6f%2f becomes /Go/. A consequence is that it is impossible to tell which slashes in the Path were slashes in the raw URL and which were %2f. This distinction is rarely important, but when it is, the code should use RawPath, an optional field which only gets set if the default encoding is different from Path.
>
>URL's String method uses the EscapedPath method to obtain the path. See the EscapedPath method for more details. 

cheers!

PS: The enterprise version includes a couple of plugins designed as a workaround for this routing limitation.

**Comment by egandro** [comment]
> KrakenD is not a reverse proxy, it's a gateway designed to build tailored, RESTful APIs for your clients. That's why wildcards are 

That is a wildcard: /World/of/bugs

Please explain why "World%2Fof%2Fbugs" is a wildcard?

If you use "World%2Fof%2Fbugs" as parameter {name} in any DotNetCore, Java Spring, ExpressJS, PHP or Go Rest Endpoints Route 1 is taken - not Route 2:

Route1: "/user/{name}"
Route2: "/user/{name}/{other}/{param}"

**Comment by egandro** [comment]
There is a working example - even with Swagger/OpenAPI support.

"World%2Fof%2Fbugs" is a non wildcard name as "foo" or "bar" or even the UTF-8 example I mentioned "%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD" 

https://github.com/swaggest/swgui/issues/21

**Comment by egandro** [comment]
I wrote a small example demonstrating the bug:

https://github.com/egandro/greeter

Go code is included. The REST Api also has a Swagger/OpenAPI UI.

I am trying to create a patch request.

**Comment by egandro** [comment]
Very simple fix:

Check PR at - https://github.com/devopsfaith/krakend-ce/pull/291

**Comment by alombarte** [comment]
Hi,

I've spoken with the team about this issue, as this is something we designed 4 years ago, and my memory wasn't up to date :)

First of all, let me thank you for the time you spent on the issue. I felt like I needed to elaborate a little more, so you are not frustrated despite having done the work.

The fix you are submitting does what you would expect, and it's a good solution for what you are currently seeking. As @kpacha pointed, we chose not to enable the UseRawPath flag (this is what your PR #291 does).

I understand that this change works for your specific scenario, but it cannot be applied as a generic solution for all users. 

You are facing a known caveat that we agreed and decided to have when we designed the product. We have other limitations like not defining static routes that contain `{}`, `:` or other reserved characters. For instance, `/{oh}/{dear}/wont:work`. Our documentation is sparse in detail, and I should improve it. 

**We chose to sacrifice a few things** during the design phase to have a flexible and secure gateway. There are restrictions that we can work around and others that not. We consider this is not one of these. 

Why? Because some of the benefits like **easy hardening of backends** surpass by far any other cons when the gateway is used in enterprise environments. It's important to understand that at the gateway-path level `%2f` is not the same as `/` . Tools that consume it can replace one with the other without any problem.

Following the hardening topic, this is one of the top 5 security measures we took when we designed the gateway —decisions that affect the security, performance, and how cacheable are responses, see:

- Input data:
  - no req headers by default
  - no query strings by default
  - no encoded req params

- Responses:
  - no status codes by default
  - no resp headers by default

The advantages of this design are clear:

**If your service receives only the parameters you are expecting explicitly and without encoding (URL, ASCII, etc), it's much harder to become a victim of typical attacks such as SQL injection, headers injection, XSS, Nmap exploits, etc.**

The gateway is the API that end-users are consuming, and to our eyes, the backend is an implementation detail. And yes, we are aware that today we offer features that allow users to choose `*` to pass query strings or headers (although we strongly discourage to do that), or to use massively `no-op`. Or that if we offered wildcards on the open source they would be massively adopted. But when users choose to do this, it's not our design decision, but their implementation choice. I wouldn't recommend such a high exposure of their systems.	

Finally, when large Enterprises questions security policies and how we audit them, we have a confident answer. We want to protect users by default, and this change would expose them.

Thanks

**Comment by egandro** [comment]
Well the generic solution should be to handle URIs according to https://tools.ietf.org/html/rfc3986.

My solution does. You you define your univiers as rfc3986 and  "no : and no / - either urlencoded or not".

1) please put that in the documentation of KrakenD - that it's not supporting the full realm of RFC URIs.
2) give the UseRawPath as option to the krakend.conf

Both ways make me happy :)

ATM I can fork the source.

**Comment by amarktl** [comment]
Hi,

@alombarte  thank you for your explanation - but i am a bit confused.

> It's important to understand that at the gateway-path level %2f is not the same as /

But due to the decoding that is happening exactly the opposite is happening. The correctly encoded parameter is decoded and generates a faulty URL. 

Also i do not understand how the security should be improved by this. If there is a correctly encoded parameter i would expected it to be passed to the backend,if it is configured.

BR,
Alex

**Comment by egandro** [comment]
> But due to the decoding that is happening exactly the opposite is happening. The correctly encoded parameter is decoded and generates a faulty URL.

That's my point. If krakenD only supports a subset of RFC URIs - for security reasons - I am cool with that.

**Comment by kpacha** [comment]
@amarktl I think that was a typo. It should be

> It's important to understand that at the gateway-path level %2f is the same as /

**Comment by egandro** [comment]
@amarktl let me make a realword example with company names

**United States**

name = "ACME Inc"

This encodes to: ACME%20Inc

**Denmark**

<https://en.wikipedia.org/wiki/Aktieselskab>

name = "ACME a/s"

This encodes to: ACME%20a%2Fs

Conclusion - for security reasons "ACME a/s" is not supported?

I am sure we find company, names, ... having / and :

**Comment by amarktl** [comment]
@kpacha , @alombarte 

Imho the gateway models the API for the consumer and not supporting these chars on gateway level means to limit the _*data*_ which can be used. I do not think the a gateway should do this. 

Additional @alombarte  stated that it was decided to not support encoded request parameters, but encoded parameters in the query part are working just fine. 

So just for my understanding; Why is limiting the ability to use certain chars on path parameters improving the security?

BR

**Comment by egandro** [comment]
> Imho the gateway models the API for the consumer and not supporting these chars on gateway level means to limit the __data__ which can be used. I do not think the a gateway should do this.

I don't understand this :( 

Did you check the testcase I included?

**Comment by amarktl** [comment]
@egandro  i checked the test cases you provided and i think they are working fine - i included your changes in my local fork as well. :) 

My statement above was targeted at the current handling of krakenD - which is faulty imho.

BR
