### ISSUE TITLE
Skip backend request on conditions(lua or alternatives)

### ISSUE THREAD

**Issue by tiberiu89** [devopsfaith/krakend-ce#347]
**Describe what are you trying to do**
I'm searching for a way to skip certain backend calls if some criteria is met. Currently I need to check if a query param is there and not empty. I feel a bit of a lack of documentation on this. I'm trying custom lua scripts.

Is there a way to actually stop a request from happening and maybe return a new empty response back to the endpoint instead of what the backend would have returned? Also make it so it doesn't count as an error.

Documentation does mention some helper called http_response. Where is this applicable in the pipeline(pre or post backend call?). I'm open to any solution(lua, CEL, Martian combination)

**Comment by tiberiu89** [comment]
Coming back with a workaround I could use

- my API backend supports a _mock=true query param and a _mockType= params. If these are present, request is skipped, then response is returned immediately with respective empty type.
- on krakend side, I just need to check in the backend if request has a specific query param, and if it meets the condition, add the  mentioned special query params above into the request query params that is going to the backend

All good, seemed easy to implement, but then bottleneck again. I cannot seem to be able to change request query via a lua script in the "pre" section of a backend proxy. Tried `local r = request.load(); r:query('_mock', 'true') `. Then tried other combinations. 

Having no success with this, I went to martian modifiers. Again bottleneck
```json
 "github.com/devopsfaith/krakend-martian": {
        "querystring.Filter": {
          "scope": ["request"],
          "name": "employeeIds",
          "value": "",
          "modifier": {
            "fifo.Group": {
              "scope": ["request"],
              "modifiers": [
                {
                  "querystring.Modifier": {
                    "scope": ["request"],
                    "name": "_mock",
                    "value": "true"
                  }
                },
                {
                  "querystring.Modifier": {
                    "scope": ["request"],
                    "name": "_mockType",
                    "value": "array"
                  }
                }
              ]
            }
          }
        }
      }


This doesn;t work, querystring.Filter is not valid. Is there a reason why only a subset of the martian modifiers are there?
```

**Comment by jan4984** [comment]
filter the backend or endpoint?

**Comment by tiberiu89** [comment]
I'm currently using this regex filter instead, to change query string completely on the backend side.
It would still be nice to have all martian transformations available. Or even better, as in the original question, posibility to completely skip a backend on certain conditions, and maybe return some default static/mock result(lua script will do). I wasn't able to stop the request and return a custom response in lua script with what I've tried at that moment. I'm not saying I haven't missed something.


```json
    "github.com/devopsfaith/krakend-martian": {
        "url.RegexFilter": {
          "scope": ["request"],
          "regex": "(?:\\?|&)employeeIds=(?:&|$)",
          "modifier": {
            "url.Modifier": {
              "scope": ["request"],
              "query": "_skip=true&_skipType=array"
            }
          }
        }
```

**Comment by alombarte** [comment]
I am no expert in the Lua implementation, but maybe you could use the custom_error with a 200? That should prevent querying the backend when your logic applies: https://www.krakend.io/docs/endpoints/lua/#custom_error

**Comment by jan4984** [comment]
"skip a backend on certain conditions" is not supported now.

**Comment by alombarte** [comment]
Skipping a backend on conditions is supported by CEL. I'll try to elaborate a working example (and will document this later on):

The following example combines the sequential proxy with the CEL component. You can copy and paste this example and start KrakenD with the krakend run -d flag. Here is what it does:

- The backend 0 (first item in the backend list) calls the URL `/__debug/0`. This backend returns the object `{"message": "pong"}`.
- The rest of the backends will be executed one by one in the order defined, as the proxy is defined as sequential.
- The next backend 1 will call `/__debug/1?ignore=pong`, as pong is the value of `resp0_message`. We are using an ignore querystring as if you were unable to modify your backend URL, but it could be part of the URL (e.g: `/__debug/1/{resp0_message}`). It is mandatory that you use a `resp_` in the URL to make KrakenD fill the request parameters in the sequential calls. In addition, as it has a CEL expression inside, this backend will be called ONLY if the response of the backend 0 contains a message field. Notice that the backend does not have access to the body of the previous call, but it has access to the parameters in the url_pattern. Thus, we can use the req_params and access any {parameter} as req_params.Resp0_parameter. All parameters capitalize the first letter (req_params.Resp0_parameter)
- The backend 2 will be triggered always, but will return the content for aggregation only when the response of the backend has a `pong` string in the response. Notice also that since we are working with the response, the `sequence-2` group is inside the expression.
- The backend 3 will be called only of the original request contains a querystring foo
- The backend 4 will never be called, and is skipped, as the endpoint does not define a `{NEVER_CALLED_BACKEND}` parameter

```
{
    "version": 2,
    "host": [
        "http://localhost:8080"
    ],
    "endpoints": [
        {
            "endpoint": "/cel",
            "querystring_params": [
                "foo"
            ],
            "backend": [
                {
                    "url_pattern": "/__debug/0"
                },
                {
                    "url_pattern": "/__debug/1/?ignore={resp0_message}",
                    "group": "sequence-1",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-cel": [
                            {
                                "check_expr": "has(req_params.Resp0_message)"
                            }
                        ]
                    }
                },
                {
                    "url_pattern": "/__debug/2",
                    "group": "sequence-2",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-cel": [
                            {
                                "check_expr": "resp_data.sequence-2.message == 'pong'"
                            }
                        ]
                    }
                },
                {
                    "url_pattern": "/__debug/3",
                    "group": "sequence-3",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-cel": [
                            {
                                "check_expr": "has(req_querystring.foo)"
                            }
                        ]
                    }
                },
                {
                    "url_pattern": "/__debug/4",
                    "group": "sequence-4",
                    "extra_config": {
                        "github.com/devopsfaith/krakend-cel": [
                            {
                                "check_expr": "has(req_params.NEVER_CALLED_BACKEND)"
                            }
                        ]
                    }
                }

            ],
            "extra_config": {
                "github.com/devopsfaith/krakend/proxy": {
                    "sequential": true
                }
            }
        }
    ]
}
```

**Comment by ba11b0y** [comment]
@alombarte Yes this works fine with `krakend run -d `
How can I get this working with a martian proxy served through gin router.
Thanks!
