### ISSUE TITLE
Randomly get connection reset

### ISSUE THREAD

**Issue by karnphongkie** [devopsfaith/krakend-ce#395]
**Describe what are you trying to do**
I simply run KrakenD on k8s and connect to backend service and when running I'll get a random connection reset like

**Logs**
If applicable, any logs you saw in the console and debugging information
`read tcp 10.36.3.223:43510->10.36.3.234:9000: read: connection reset by peer`

**Comment by ericlacher** [comment]
this might be related to my issue (https://github.com/devopsfaith/krakend-ce/issues/396). Eventually, on querying client side, I am also getting

`('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

However, I do not know whether the root cause is the same, as this symptom can be caused by a lot of things.

**Comment by kpacha** [comment]
I don't think this is related to KrakenD...

as commented here: https://github.com/golang/go/issues/20960#issuecomment-348405178

> If you get broken network connections, they might be real (a peer really did disconnect), or they might be from hitting kernel limits on one of the sides.

check your networking and kernel configuration (ulimits, etc) and maybe your k8s instances (free disk space, etc)
