### ISSUE TITLE
own plugin: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by fabmade** [devopsfaith/krakend-ce#411]
Hi together,

i have a problem with my self created plugin, when i run krakend the following error appears

```
[KRAKEND] 2022/02/04 - 13:10:42.810 ▶ WARNIN loading plugins: plugin loader found 1 error(s): 

opening plugin 0 (plugin/authserviceplug.so): plugin.Open("plugin/authserviceplug.so"): /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /etc/krakend/plugin/authserviceplug.so)
```

someone has an idea what can be the problem?

I created the plugin via: 

```go build -buildmode=plugin -o authserviceplug.so```

thanks
fabian

**Comment by fabmade** [comment]
i found a solution/workaround.

the problem appears, if i build the plugin with ubuntu 21.10 and go version 1.16.4
If i build it with ubuntu 20.04 (same go version) it will work correct.

I think the new ubuntu use an other version of GLIBC, but strange that this has an impact on go...

But i think this is not an krakend problem, but rather a golang problem therefore i close the ticket.

**Comment by kpacha** [comment]
Hi, @fabmade , I think we should also track that detail in order to simplify the plugin build process. Thanks for the heads up.

On the other hand, as you said, it's a constraint added by the go plugin package itself. It loads plugins using CGO, thus the version of the c lib used when compiling the binary and the plugins should be the same, that's why we recommend to build the plugins on the same docker image we used to build the binary

Cheers!
