### ISSUE TITLE
Passing a new object as context to template 

### ISSUE THREAD

**Issue by yanivshiloah** [devopsfaith/krakend-ce#418]
Hey, I'm a bit new to krakend and Go templating so sorry :)

I'm trying to pass a new object with multiple properties as a context to a template.

I have a auth0_backend template 
```
"github.com/devopsfaith/krakend-jose/validator": {
    "alg": "RS256",
    "audience": ["{{ env "AUTH_AUDIENCE"}}"],
    "jwk-url": "https://{{ env "AUTH_DOMAIN" }}/.well-known/jwks.json",
    "scopes_key": "scope",
    "scopes": {{ marshal .scopes }},
    "propagate-claims": [
        ["sub", "x-user"],
        ["http://aaa/user_attributes", "x-user-attributes"]
    ]
}
```

And i'm trying to pass this template a context with multiple properties such as scopes, roles, etc'.

```
"extra_config": {
        {{ template "auth0_backend.tmpl" {roles: ["admin"], scopes: ["read:test"} }}
}
```

Can I somehow achieve that?

Thanks.

**Comment by alombarte** [comment]
Hi @yanivshiloah ,
KrakenD uses standard Go [text/templates](https://pkg.go.dev/text/template). You should pass to templates the "calculated value" inside an object, rather than creating new objects as you cannot pass `{}` inside the template clause.

In scenarios like this, my personal approach would be creating something like this:
**settings/permissions.json**
```
{
    "is_admin": {
        "r": ["admin"],
        "s": ["read:test"]
    },
    "is_sad": {
        "r": ["sad"],
        "s": ["read:nothing"]
    }
}
```
And when calling the template:
```
"extra_config": {
        {{ template "auth0_backend.tmpl" .permissions.is_admin }}
}
```
Hope this helps

**Comment by yanivshiloah** [comment]
Thanks a lot, good idea! :)
