### ISSUE TITLE
Loading plugins in docker devopsfaith/krakend 

### ISSUE THREAD

**Issue by peturssonstefan-ikea** [devopsfaith/krakend-ce#491]
Hi!

Im trying to run krakend using the docker image provided from devopsfaith/krakend. 

The application starts, but my plugins (which are build outside of the docker image, as it's an alpine image), have trouble being loaded. 
Initially I encountered the problem with CGO_ENABLED, which I've now set to 0. 
Then there was a problem with the GO_VERSION being different from what krakend had been built with (I found the version in the Makefile on this github repo), so that was fixed too. 
But now I've encountered a problem with the "net" package being a different version too. 

It feels to me like I'm going to wrong way about this. How would you add plugins to the docker image? 

The specific errors I'm seeing for my plugins now are: 

`2022/05/04 07:59:56 KRAKEND DEBUG: [SERVICE: Plugin Loader] Starting loading process
2022/05/04 07:59:56 KRAKEND DEBUG: [SERVICE: Executor Plugin] plugin #0 (/plugins/krakend-debugger.so): plugin.Open("/plugins/krakend-debugger"): plugin was built with a different version of package net
2022/05/04 07:59:56 KRAKEND DEBUG: [SERVICE: Handler Plugin] plugin #0 (/plugins/krakend-debugger.so): plugin.Open("/plugins/krakend-debugger.so"): plugin was built with a different version of package net (previous failure)
2022/05/04 07:59:56 KRAKEND DEBUG: [SERVICE: Modifier Plugin] plugin #0 (/plugins/krakend-debugger.so): plugin.Open("/plugins/krakend-debugger.so"): plugin was built with a different version of package net (previous failure)
2022/05/04 07:59:56 KRAKEND DEBUG: [SERVICE: Plugin Loader] Loading process completed
`

Thanks!

**Comment by taik0** [comment]
Hi @peturssonstefan-ikea 
Things to take into account when developing plugins:

- You NEED CGO.
- You need to build the plugin using the EXACT same GO version used to compile the binary that will load the plugin.
- You need to build the plugin using the same GLIBC (MUSL on alpine)
- Any dependency being used in the plugin, that also is used in the binary, need to be the exact same version.
- You can check the differences between dependencies using the `check-plugin` subcommand from KrakenD.

The easiest way to achieve the required environment is to check all the required versions in the `Makefile` we use to build KrakenD.

https://github.com/devopsfaith/krakend-ce/blob/master/Makefile#L22 <-- GOLANG VERSION
https://github.com/devopsfaith/krakend-ce/blob/master/Makefile#L24 <-- ALPINE VERSION
Resulting docker image: `golang:${GOLANG_VERSION}-alpine${ALPINE_VERSION}`

Check the Dockerfile since alpine need to install some tools to be able to build correctly:
https://github.com/devopsfaith/krakend-ce/blob/master/Dockerfile#L5

**Comment by peturssonstefan-ikea** [comment]
Thanks for the quick response taik0, it's much appreciated! I'll try it out and hopefully get it up and running!

**Comment by peturssonstefan-ikea** [comment]
Alright, it's up and running. Thanks again for the help.
In relation to: 
_Any dependency being used in the plugin, that also is used in the binary, need to be the exact same version._
Does anyone have any recommendations on tools that can keep the two .mod files in sync? Or is this better handled manually?

**Comment by taik0** [comment]
I'm glad that it helped.

It's a very cumbersome process, what usually works is to check with the `check-plugin` KrakenD command:
```
➜ [my-plugin-directory]%  krakend check-plugin -l DARWIN-11.6.3
11 incompatibility(ies) found...
github.com/Shopify/sarama
	have: v1.31.0
	want: v1.27.2
github.com/golang/snappy
	have: v0.0.4
	want: v0.0.3
github.com/klauspost/compress
	have: v1.13.6
	want: v1.13.1
github.com/pierrec/lz4
	have: v2.6.1+incompatible
	want: v2.6.0+incompatible
github.com/rcrowley/go-metrics
	have: v0.0.0-20201227073835-cf1acfcdf475
	want: v0.0.0-20200313005456-10cdbea86bc0
...
```

Uusually setting the same version is enough, but you can encounter problems if a lot of common deps are used by KrakenD and the plugin. An "easy" way is to put `replace` directives in your plugin go.mod to make it match the KrakenD ones.

**Comment by alombarte** [comment]
Hi @peturssonstefan-ikea, 

I am closing this issue as I understand there is nothing else actionable in this issue. Let me know otherwise
