### ISSUE TITLE
add feature to build backend fallback chains

### ISSUE THREAD

**Issue by softwarelimits** [devopsfaith/krakend-ce#61]
add feature to build backend fallback chains, like nginx try_files for backends: try_backends

**Comment by alombarte** [comment]
Please elaborate

**Comment by alombarte** [comment]
Thanks for your clarification.

This philosophy is the opposite to the [KrakenD Rules](https://github.com/devopsfaith/krakend/blob/master/docs/OVERVIEW.md), specifically the one "Failing fast is better than succeeding slow".

I think that the best resolution to this problem is to rely on your service discovery system, which is capable of giving you a probably healthy backend in the first place.

Regarding what is happening behind the scenes, KrakenD uses the whole list of available backends to do a round robin and pick one (for `concurrency=1`) or several of them (for `concurrency > 1`). If the backend call fails then you have (at least) a partial failure in the response, which will be reflected in the response headers.

Read also this comment regarding partial failure: https://github.com/devopsfaith/krakend-ce/issues/32#issuecomment-416601561

I close the issue as it won't be implemented, but feel free to add any other comment.
