### ISSUE TITLE
add feature to store raw api result data

### ISSUE THREAD

**Issue by softwarelimits** [devopsfaith/krakend-ce#65]
add feature to **store** raw api result data in a configurable way for debugging or historical reasons.

I know this will kill performance. For some use cases, however, persisting information can be more important than performance (reporting, debugging, etc).

**Comment by kpacha** [comment]
hi, @softwarelimits 

I think you should check the [krakend-spew](https://github.com/devopsfaith/krakend-spew) module. It will show you even the intermediate states of every request and response.

We did not add it to the CE because its huge impact on the performance and the pressure it adds to the filesystem. Whenever we need to do it on production environments we rather use `tcpdump` and some pcap inspector like wireshark.

Cheers

**Comment by kpacha** [comment]
hi, @softwarelimits ,

the latest version of the spew module now supports injecting a custom DumperFactory for dumping the inspected data to backends other than the local FS.

as you can see, we have not changed our minds regarding the introduction of the spew module into the official binary, but we are eager to hear more opinions, thoughts and proposals. interesting ideas appears in the middle of interesting discussions

cheers!
